In [ ]:
import numpy  as np
import pandas as pd

np.random.seed(5678)
scores = np.random.randint(50,101,size=(50,5))
students = pd.DataFrame(scores,
            index=[f"學生{x}" for x in range(1,51)],
            columns=["國文", "英文", "數學", "生物", "物理"])
students

In [5]:
students['國文']
students[['國文','數學']]

       國文   數學
學生1    73   63
學生2    81   64
學生3    65   68
學生4    55   76
學生5    69   75
學生6    75   92
學生7    54   84
學生8    63   52
學生9    68   70
學生10   82   82
學生11   98  100
學生12   58   84
學生13   69   94
學生14   91   83
學生15   79   87
學生16   96   88
學生17   65   69
學生18   63   84
學生19   51   88
學生20   97   90
學生21   52   71
學生22   81   68
學生23   93   68
學生24   57   50
學生25   55   67
學生26   73   54
學生27   79   63
學生28   92   67
學生29   60   96
學生30   80   74
學生31   51   72
學生32   71   88
學生33   71   57
學生34   80   57
學生35   63   68
學生36   82   92
學生37   85   69
學生38   96   67
學生39   54   56
學生40   95   81
學生41   80   80
學生42   75   82
學生43   99   98
學生44   82   61
學生45  100   98
學生46   52   57
學生47   92   52
學生48   58   55
學生49   84   90
學生50   89   65

In [ ]:
sum_series = np.sum(students,axis=1)
average_series = np.mean(students, axis=1)
average_series

In [ ]:
students_finish = students.copy()
students_finish['總分'] = sum_series
students_finish['平均'] = average_series
students_finish